### ISSUE TITLE
[Troubleshooting] Autoscroll

### ISSUE THREAD

**Issue by leandrommedeiros** [SeeSharpSoft/intellij-file-preview#17]
Preview Editor tab won't open if the Project View has the "Autoscroll to Source" option enabled.

**Comment by SeeSharpSoft** [comment]
@leandrommedeiros Thanks for reporting and your feedback at the plugin repository!

I verified the described behavior and thought it is a bug at first. After investigating into the purpose of this option, I come to the conclusion that the current behavior is correct. [It is stated in the help](https://www.jetbrains.com/help/idea/navigating-through-the-source-code.html#scroll_to_from_source):

>  You can also select the Autoscroll to Source option. In this case, when you click a file in the Project view, IntelliJ IDEA will automatically open it in the editor.

So thats what currently happens if "Autoscroll to Source" option is enabled, the functionality of the option is kept as it was intended.

In case I would change behavior so that the Preview Editor tab would be used, then enabling/disabling "Autoscroll to Source" wouldn't have any effect at all anymore, which I would consider a bug then.

**Comment by leandrommedeiros** [comment]
@SeeSharpSoft I think my comment was too short and therefore I didn't make myself clear enough: I understand that this is the expected behavior but, since I've had that option enabled for years now, it took me a while to figure it out why the plugin wasn't working properly. I'm pretty sure a lot of people might face the same problem so I thought maybe you could add this information to a troubleshooting section in the README, or even add an option to the plugin in order to override the IDE's feature. Once again thanks for the awesome solution!
