### ISSUE TITLE
Do not preview .sln file on solution open

### ISSUE THREAD

**Issue by amelkor** [SeeSharpSoft/intellij-file-preview#54]
Currently when you open a solution in Rider the solution .sln file gets opened in preview which is kinda annoying. Usually you do not need to modify the .sln file at all so it would be nice to just ignore .sln files for preview. It can be edited manually if needed.

**Comment by SeeSharpSoft** [comment]
Can you elaborate on the issue? I can't reproduce it (see ScreenCapture - the interaction at the end is just show-casing that the plugin is actually installed)

![H7D4skTRWf](https://user-images.githubusercontent.com/3205800/73090050-dde6c280-3ed7-11ea-8e4c-8987d87b8cd9.gif)

**Comment by amelkor** [comment]
![image](https://user-images.githubusercontent.com/30626539/73169661-9d708a00-410d-11ea-8996-c0ea6f5658a6.png)


![rider_solution_issue](https://user-images.githubusercontent.com/30626539/73169134-78c7e280-410c-11ea-8a80-0ba30fd09fb1.gif)

Steps:

1. Open Rider from JetBrains Toolbox
2. Click on a solution
3. The solution will be opened, the .sln file will be selected by default and previewed.

Desired behaviour:
The Program.cs/empty space should be shown

As you see I have the Program.cs file already opened at previous solution launch. So I'd prefer to start with Program.cs or any other last opened file. In case there're no files opened, empty space should be shown.

**Comment by SeeSharpSoft** [comment]
Thanks for sharing, I was able to reproduce the described behavior by switching to "Solution" view (instead of "File System"). In this view the root node "DemoSolution" seems to be associated with the .sln file and is selected by default. So the current behavior is actually as it is supposed to be, changing this behavior I would consider a bug - introducing arbitrary exception for certain files as well.

However, I could imagine some kind of configuration to let the end-user decide which (and whether) file-types are ignored from the preview. This is from my perspective a low priority enhancement - contributions are welcome.

**Comment by amelkor** [comment]
Agreed with that. Providing some configuration possibilities would be a really good way to manage
