### ISSUE TITLE
ide.tree.collapse.recursively setting keeps resetting

### ISSUE THREAD

**Issue by WorkForPizza** [SeeSharpSoft/intellij-file-preview#95]
Hi,

My IDE keeps randomly resetting the "ide.tree.collapse.recursively" setting. I submitted a bug report to the JetBrains team, who told me the issue is caused by this plugin. They singled out [this line in the source](https://github.com/SeeSharpSoft/intellij-file-preview/blob/b61c5a07b39ca1755dee1fe55ea1b4315dc7f1d1/src/main/java/net/seesharpsoft/intellij/plugins/filepreview/PreviewSettings.java#L172) as the culprit. You can see my original bug report and their response [here](https://youtrack.jetbrains.com/issue/IDEA-307058/File-tree-recursive-collapse-setting-keeps-resetting). 

Any idea what I need to do to fix this behavior? Is this a bug in the plugin, or a user error on my end? 

Thanks!

**Comment by SeeSharpSoft** [comment]
Yes, this plugin is alters the setting but can be adjusted in the settings: https://github.com/SeeSharpSoft/intellij-file-preview#keep-expandcollapse-state-enabled

Please note: This project is no longer maintained due to an added [built-in functionality in IntelliJ](https://www.jetbrains.com/help/idea/using-code-editor.html#preview-tab) to preview files, which works quite similar to this plugin.

**Comment by WorkForPizza** [comment]
Oh, nice! Thanks so much
